name: CI/CD Pipeline
on:
  push:
    branches:
      - main

jobs:

  build:
    name: Build and Test
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'
      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Check RDS Status
        id: check-rds
        run: |
          RDS_STATUS=$(aws rds describe-db-instances --db-instance-identifier ${{ secrets.RDS_IDENTIFIER }} --query "DBInstances[0].DBInstanceStatus" --output text)
          echo "Current RDS Status: $RDS_STATUS"
          if [ "$RDS_STATUS" = "stopped" ]; then
            echo "Starting RDS..."
            aws rds start-db-instance --db-instance-identifier ${{ secrets.RDS_IDENTIFIER }}
            while [ "$(aws rds describe-db-instances --db-instance-identifier ${{ secrets.RDS_IDENTIFIER }} --query 'DBInstances[0].DBInstanceStatus' --output text)" != "available" ]; do
              echo "Waiting for RDS to be available..."
              sleep 20
            done
          fi
      - name: Check EC2 Status
        id: check-ec2
        run: |
          EC2_STATUS=$(aws ec2 describe-instances --instance-ids ${{ secrets.EC2_INSTANCE_ID }} --query "Reservations[0].Instances[0].State.Name" --output text)
          echo "Current EC2 Status: $EC2_STATUS"
          if [ "$EC2_STATUS" = "stopped" ]; then
            echo "Starting EC2..."
            aws ec2 start-instances --instance-ids ${{ secrets.EC2_INSTANCE_ID }}
            while [ "$(aws ec2 describe-instances --instance-ids ${{ secrets.EC2_INSTANCE_ID }} --query 'Reservations[0].Instances[0].State.Name' --output text)" != "running" ]; do
              echo "Waiting for EC2 to be running..."
              sleep 20
            done
          fi
      - name: Update db url
        run: sed -i 's|<db_url>|${{ secrets.DATABASE_URL }}|' src/main/resources/application.properties
      - name: Update db username
        run: sed -i 's|<db_username>|${{ secrets.DATABASE_USERNAME }}|' src/main/resources/application.properties
      - name: Update db password
        run: sed -i 's|<db_password>|${{ secrets.DATABASE_PASSWORD }}|' src/main/resources/application.properties
      - name: Build Project and Run Tests with Coverage
        run: mvn clean verify -Pcoverage -Dsonar.token=${{ secrets.SONAR_TOKEN }}
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/leds-devops:latest .
      - name: Publish image to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/leds-devops:latest

  sonar:
    needs: build
    name: SonarQube Analysis
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'
      - name: Cache SonarQube packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Update db url
        run: sed -i 's|<db_url>|${{ secrets.DATABASE_URL }}|' src/main/resources/application.properties
      - name: Update db username
        run: sed -i 's|<db_username>|${{ secrets.DATABASE_USERNAME }}|' src/main/resources/application.properties
      - name: Update db password
        run: sed -i 's|<db_password>|${{ secrets.DATABASE_PASSWORD }}|' src/main/resources/application.properties
      - name: Run Tests and Generate Coverage Report
        run: mvn clean verify -Pcoverage -Dsonar.token=${{ secrets.SONAR_TOKEN }}
      - name: Build and analyze with SonarQube
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          mvn sonar:sonar \
            -Dsonar.projectKey=jhonatademuner_leds-devops \
            -Dsonar.organization=jhonata-demuner-org \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml \
            -Dsonar.token=${{ secrets.SONAR_TOKEN }}
  

  deploy:
    needs: build
    runs-on:
      - aws-ec2-leds-devops
    steps:
      - name: Pull image from Docker Hub
        run: sudo docker pull ${{ secrets.DOCKER_USERNAME }}/leds-devops:latest
      - name: Delete old container
        run: sudo docker rm -f leds-devops-container || true
      - name: Run Docker Container
        run: sudo docker run -d -p 8080:8080 --name leds-devops-container ${{ secrets.DOCKER_USERNAME }}/leds-devops:latest
